### ISSUE TITLE
If payment fails, Wirecard QENTA HTTPClient will be blocked by SW statistic plugin / BOT filter

### ISSUE THREAD

**Issue by klausmad** [wirecard/shopware-wcs#38] opened 2016-11-28 17:49 UTC
For this notice in your description: For Shopware versions higher than 5.2.8 our plugin is incompatible with the statistics plugin from Shopware AG. >> here my workaround:

If a payment like paypal, sofort, eps or other external managed payments fails or customer stop the payment on the external paymentsite or it happens a timeout, you normaly come back to the page  http://[shop]/checkout/confirm. Because of the USER AGENT name of the wirecard page QENTA HTTPClient  the return to this page will be blocked by shopware BOT Filter and the user logs out. So the customer will see the Login or Register Page and will maybe not find back to the cart so easy....

Workaround: Remove "HTTPClient" from the BOTList in the SW Plugin Statistics, clear cache. After this the return to the http://[shop]/checkout/confirm will work again (tested on php7, SW 5.2.9)

For the future maybe wirecard must rename their HTTPClient so the USER AGENT in the http header has not the Words "HTTPClient" inside ....

**Comment by jakubpolomsky** [comment] 2016-11-29 08:09
Hello,

unfortunately this is no viable solution. There are many customers and shop systems relying on these headers. Shopware is the only one where httpclient is blacklisted (since 5.2.9) and where the plugin taking care of blacklisting doesn't work properly. When we found the cause of the issue we tried removing this word from the listing, we tried disabling the plugin but only after uninstalling the statistics plugin the issue resolved. I will close this issue now, as we really cannot modify the headers without causing issues among hundreds of our clients.

Kind regards

**Closed by jakubpolomsky** 2016-11-29 08:09 UTC
